# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


common: &common
  adapter: postgresql

dev: &dev
  <<: *common
  host: localhost
  username: "hery"
  password: "123456"

development:
  <<: *dev
  database: mountseek_dev

test:
  <<: *dev
  database: mountseek_test

production:
  <<: *common
  host: localhost
<% if `uname -n`.strip == "staging" %>
  database: mountseek_dev
  username:
  password:
<% else %>
  database: mountseek_dev
  username:
  password:
<% end %>
